name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (Chromium)
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          VALID_EMAIL: ${{ secrets.VALID_EMAIL }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
        run: xvfb-run --auto-servernum npx playwright test --project=frontend-chromium

      - name: Run Playwright tests (Firefox)
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          VALID_EMAIL: ${{ secrets.VALID_EMAIL }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
        run: xvfb-run --auto-servernum npx playwright test --project=frontend-firefox

      - name: Run Playwright tests (WebKit)
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          VALID_EMAIL: ${{ secrets.VALID_EMAIL }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
        run: xvfb-run --auto-servernum npx playwright test --project=frontend-webkit

      - name: Run Playwright tests (Backend)
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          VALID_EMAIL: ${{ secrets.VALID_EMAIL }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
        run: npx playwright test --project=backend
